### ISSUE TITLE
Error with grunt-contrib-connect 0.8.0

### ISSUE THREAD

**Issue by zenhunt** [drewzboto/grunt-connect-proxy#65]
This plugin is broken in usage with grunt connect 0.8.0, updating to this version will result in the following error:

Running "connect:devproxy" (connect) task
Verifying property connect.devproxy exists in config...OK
File: [no files]
Options: protocol="http", port=9997, hostname="closedhost", base="tmp", directory=null, keepalive=false, debug=false, livereload, open=false, useAvailablePort=false,onCreateServer=null, middleware=undefined
**Warning: Arguments to path.resolve must be strings Use --force to continue.**

Please fix. :)

Best Regards,

@zenhunt

**Comment by zenhunt** [comment]
Tony! n1. Thank you.

**Comment by merriam** [comment]
Whee!  Is still broken btw.  Will try the workaround.
