### ISSUE TITLE
Host header not properly set in proxied request

### ISSUE THREAD

**Issue by niltz** [drewzboto/grunt-connect-proxy#69]
here is my config:

``` javascript
connect: {
      server: {
        options: {
          port: 8000,
          base: 'src',
          keepalive: true,
          middleware: function (connect, options) {
            var proxy = require('grunt-connect-proxy/lib/utils').proxyRequest;
            return [
              proxy,
              connect.static(options.base[0]),
              connect.directory(options.base[0])
              ];
          }
        },
        proxies: [{
          context: '/otherapi',
          host: 'www.other.com',
          port: 80,
          https: false,
          headers: {
            'host': 'www.other.com'
          },
          rewrite: {
            '^/otherapi': '/api'
          }
        }]
      }
    }
  });
```

Which works, and successfully proxies all XHR requests to `http://localhost:8000/otherapi` to `http://www.other.com/api`. However, without the headers option, the proxy doesn't work. The request is sent to the ip for `www.other.com` but the host header is still `localhost:8000` and the api request fails. I had to add the extra host header to get it to work, which I don't think should be required.

**Comment by outaTiME** [comment]
Same issue here =(

**Comment by k7n4n5t3w4rt** [comment]
Ditto for 0.2.0. Maybe it's the new way. Adding this here in case it's driving someone crazy like it did me.

I had to include "headers":

      proxies: [{
        context: '/api', // the context of the data service
        host: 'tidespy.com', // wherever the data service is running
        port: 80, // the port that the data service is running on
        headers: {
            'host': 'tidespy.com'
          }
      }],

**Comment by MattSchlobohm** [comment]
I don't even get a request sent unless I add the host header...

Packet capture with wireshark verifies, without host header, it opens connections but never sends the HTTP request...
