### ISSUE TITLE
Unable to download pdf files through the proxy

### ISSUE THREAD

**Issue by reda-alaoui** [drewzboto/grunt-connect-proxy#73]
Hi everyone,

I am unable to download pdf files through the proxy served by an ordinary servlet at `/myapp/pdfservlet/` on my tomcat server.
When I try without proxy, pdf files are correctly downloaded.

Here is my proxy configuration:
```javascript
{
	context: '/', // the context of the data service
	host: localhost, // wherever the data service is running
	port: 8080, // the port that the data service is running on
	ws: true, // Proxy websocket
	rewrite: { '^/myapp/realtime/fallback':  '/myapp/realtime'},
        excludedFileTypes: ['pdf', 'jar', 'gz']
}
```

Here is the request/response given by Chrome:

<pre>
<b>Remote Address</b>:127.0.0.1:9000
<b>Request URL</b>:http://localhost:9000/myapp/pdfservlet
<b>Request Method</b>:GET
<b>Status Code</b>:200 OK

<i><b>Request Headers</b></i>
<b>Accept</b>:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
<b>Accept-Encoding</b>:gzip,deflate,sdch
<b>Accept-Language</b>:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,es;q=0.2
<b>Connection</b>:keep-alive
<b>Host</b>:localhost:9000
<b>Referer</b>:http://localhost:9000/myapp/jsp/foo.jsp
<b>User-Agent</b>:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.103 Safari/537.36

<i><b>Response Headers</b></i>
<b>connection</b>:close
<b>content-disposition</b>:filename="foo.pdf"
<b>content-language</b>:fr-FR
<b>content-type</b>:application/pdf;charset=UTF-8
<b>date</b>:Wed, 10 Sep 2014 17:36:13 GMT
<b>server</b>:Apache-Coyote/1.1
<b>transfer-encoding</b>:chunked

</pre>

It also happens on `.gz` files.
It seems that the connection is closed before the end of the file because the pdf is just blank.

Am I missing something?

**Comment by pocketmax** [comment]
I've got the same problem...

```
var http = require('http'),
    httpProxy = require('http-proxy'),
    proxy = httpProxy.createProxyServer({});

http.createServer(function(req, res) {

    proxy.web(req, res, { target: req.url });

}).listen(8005, function() {
    console.log('proxy listening on port 8005');
});
```
this works...
```
wget -e http://security.ubuntu.com/ubuntu/pool/main/p/php5/libapache2-mod-php5_5.3.10-1ubuntu3.15_amd64.deb
```
this does not...
```
wget -e http_proxy=127.0.0.1:8005 http://security.ubuntu.com/ubuntu/pool/main/p/php5/libapache2-mod-php5_5.3.10-1ubuntu3.15_amd64.deb
```

**Comment by webskin** [comment]
Same problem for me. Tomcat serves my pdf with `Content-Length: xxx` and the proxy 'Transfer-Encoding: chunked'. Surprisingly, when I change the extension of the url to `.png` but let `Content-Type` to `application/pdf` it works. So may be a content negotiation problem.

**Comment by jaymes-bearden** [comment]
Exact same problem with me. Does anyone have a suitable workaround for the time being?

**Comment by reda-alaoui** [comment]
A workaround would be great or at least knowing the library's layer to modify ...

**Comment by kglef** [comment]
A workaround would be sweet!

**Comment by michi88** [comment]
+1 same problem here

**Comment by AssiaAzzouzi** [comment]
I have the same problem...did anyone find the answer?

**Comment by juristr** [comment]
unfortunately not yet. Didn't have the time to look into it, but I'm very interested in a solution.

**Comment by reda-alaoui** [comment]
I just found the solution for my case!
For the record, I was using ```grunt-connect-proxy#0.1.11```.
My project was generated by Yeoman.
Yeoman generated automatically a ```package.json``` containing:
```
"devDependencies": {
    ...
    "grunt-connect-proxy": "0.1.11",
    "grunt-contrib-connect": "0.7.1",
    ...
}
```
I changed the ```grunt-contrib-connect``` version to ```0.5.0``` which is the one pulled by ```grunt-connect-proxy#0.1.11```.

That solved ```pdf``` and ```gz``` corruption !
Don't forget to disable your browser cache for your pdf fetch tests.

**Comment by k7n4n5t3w4rt** [comment]
+1 for reda-alaoui's solution.

Changing the grunt-contrib-connect version to 0.5.0 in the main package.json file and doing an "npm update" fixed the problem.

**Comment by sweco-seprst** [comment]
+1 for reda-alaoui's solution.

**Comment by Epimetheus89** [comment]
+1 for reda-alaoui's solution.

Had problems with .jpeg and .xls files. But that solution solved it. Even upgrading on newest version 0.10.1 did not help.

**Comment by Edorka** [comment]
+1 for reda-alaoui's solution.

**Comment by jrno** [comment]
+1 for reda-alaoui's solution.

**Comment by klopfdreh** [comment]
+1 for the solution mentioned by @reda-alaoui
