### ISSUE TITLE
Version 0.1.11 breaks grunt build

### ISSUE THREAD

**Issue by maikdiepenbroek** [drewzboto/grunt-connect-proxy#98]
Upon updating to 0.1.11 our grunt build broke with the following log. We were forced to downgrade to 0.1.10.

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.exports.inherits (util.js:555:43)
>>     at Object.<anonymous> (node_modules/grunt-connect-proxy/node_modules/http-proxy/lib/http-proxy/index.js:106:17)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (node_modules/grunt-connect-proxy/node_modules/http-proxy/lib/http-proxy.js:4:17)
>>     at Module._compile (module.js:456:26)

No tasks specified, running default tasks.
Running tasks: default
Warning: Task "default" not found. Use --force to continue.

**Comment by ruiaraujo** [comment]
Please update to 0.2.0.

This issue has been fixed.

**Comment by maikdiepenbroek** [comment]
I was not aware that 0.2.0 was available on npm. 

Thanks for the info :)

**Comment by Chexpir** [comment]
IMO a 0.1.12 should have been released not to break a lot of builds around the globe :-)

**Comment by ruiaraujo** [comment]
@Chexpir yup.
